import Navbar from '@components/Navbar'
import './globals.css'
import { Outfit } from 'next/font/google'
// import Footer from '@components/Footer'
import ScrollComponent from '@components/ScrollComponent'
import FooterNew from '@components/FooterNew'

const outfit = Outfit({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <Navbar />
        <ScrollComponent />
        {children}
        <FooterNew />
      </body>
    </html>
  )
}
